#!/usr/bin/python

import os
import sys
import urllib2
import xml.dom.minidom
reload(sys)
sys.setdefaultencoding('utf-8')

if __name__ == "__main__":
    argc = len(sys.argv)
    if argc < 2:
        print 'usage: dict word'
        sys.exit()
    word = sys.argv[1]
    apiurl = "http://dict.youdao.com/fsearch?q="+word
    result = urllib2.urlopen(apiurl).read()
    dom = xml.dom.minidom.parseString(result)
    content = ''
    for node in dom.getElementsByTagName('content'):
        if content == '':
            content = node.childNodes[0].data
        print node.childNodes[0].data
    fp = open(os.path.join(os.environ['HOME'],'dict.txt'),'a')
    fp.write(word + '  ' + content + '\r\n')
    fp.close()
