#!/bin/bash

command_string="google-chrome --app "

servicepath="replace to the real path"
webpath="replace to the real path"

for server in $(seq 5)
do 
    eval $command_string \"http://webus$server".englishtown.com/$servicepath"\"
    eval $command_string \"http://webus$server."englishtown.com/$webpath"\"
done
